// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace KeePassPluginDevTools.PlgxTools {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PlgxConfiguration {
        
        private PlgxConfigurationPrerequisites prerequisitesField;
        
        private PlgxConfigurationBuildCommands buildCommandsField;
        
        private string includeFilesField;
        
        private string excludeFilesField;
        
        private PlgxConfigurationPackageOutput packageOutputField;
        
        /// <remarks/>
        public PlgxConfigurationPrerequisites Prerequisites {
            get {
                return this.prerequisitesField;
            }
            set {
                this.prerequisitesField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationBuildCommands BuildCommands {
            get {
                return this.buildCommandsField;
            }
            set {
                this.buildCommandsField = value;
            }
        }
        
        /// <remarks/>
        public string IncludeFiles {
            get {
                return this.includeFilesField;
            }
            set {
                this.includeFilesField = value;
            }
        }
        
        /// <remarks/>
        public string ExcludeFiles {
            get {
                return this.excludeFilesField;
            }
            set {
                this.excludeFilesField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPackageOutput PackageOutput {
            get {
                return this.packageOutputField;
            }
            set {
                this.packageOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPrerequisites {
        
        private string keePassVersionField;
        
        private string dotNetVersionField;
        
        private PlgxConfigurationPrerequisitesOS oSField;
        
        private bool oSSpecifiedField;
        
        private PlgxConfigurationPrerequisitesPointerSize pointerSizeField;
        
        private bool pointerSizeSpecifiedField;
        
        /// <remarks/>
        public string KeePassVersion {
            get {
                return this.keePassVersionField;
            }
            set {
                this.keePassVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DotNetVersion {
            get {
                return this.dotNetVersionField;
            }
            set {
                this.dotNetVersionField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPrerequisitesOS OS {
            get {
                return this.oSField;
            }
            set {
                this.oSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool OSSpecified {
            get {
                return this.oSSpecifiedField;
            }
            set {
                this.oSSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPrerequisitesPointerSize PointerSize {
            get {
                return this.pointerSizeField;
            }
            set {
                this.pointerSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool PointerSizeSpecified {
            get {
                return this.pointerSizeSpecifiedField;
            }
            set {
                this.pointerSizeSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PlgxConfigurationPrerequisitesOS {
        
        /// <remarks/>
        Windows,
        
        /// <remarks/>
        Unix,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PlgxConfigurationPrerequisitesPointerSize {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationBuildCommands {
        
        private string preBuildField;
        
        private string postBuildField;
        
        /// <remarks/>
        public string PreBuild {
            get {
                return this.preBuildField;
            }
            set {
                this.preBuildField = value;
            }
        }
        
        /// <remarks/>
        public string PostBuild {
            get {
                return this.postBuildField;
            }
            set {
                this.postBuildField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPackageOutput {
        
        private string packageNameField;
        
        private PlgxConfigurationPackageOutputVersionSegments versionSegmentsField;
        
        private string destinationPathField;
        
        private PlgxConfigurationPackageOutputZip zipField;
        
        private PlgxConfigurationPackageOutputDeb debField;
        
        private PlgxConfigurationPackageOutputRpm rpmField;
        
        private PlgxConfigurationPackageOutputMsi msiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PackageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(PlgxConfigurationPackageOutputVersionSegments.Item3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PlgxConfigurationPackageOutputVersionSegments VersionSegments {
            get {
                return this.versionSegmentsField;
            }
            set {
                this.versionSegmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestinationPath {
            get {
                return this.destinationPathField;
            }
            set {
                this.destinationPathField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPackageOutputZip zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPackageOutputDeb deb {
            get {
                return this.debField;
            }
            set {
                this.debField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPackageOutputRpm rpm {
            get {
                return this.rpmField;
            }
            set {
                this.rpmField = value;
            }
        }
        
        /// <remarks/>
        public PlgxConfigurationPackageOutputMsi msi {
            get {
                return this.msiField;
            }
            set {
                this.msiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PlgxConfigurationPackageOutputVersionSegments {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPackageOutputZip {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPackageOutputDeb {
        
        private string packageRevisionField;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("1")]
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string PackageRevision {
            get {
                return this.packageRevisionField;
            }
            set {
                this.packageRevisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPackageOutputRpm {
        
        private string packageRevisionField1;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("1")]
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string PackageRevision {
            get {
                return this.packageRevisionField1;
            }
            set {
                this.packageRevisionField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlgxConfigurationPackageOutputMsi {
    }
}
