//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://lechnology.com/KeePass2PluginPackagerConfig", IsNullable=false)]
public partial class Plugin {
    
    private string projectPathField;
    
    private PluginPrerequisites prerequisitesField;
    
    private PluginBuildCommands buildCommandsField;
    
    private string includeFilesField;
    
    private string excludeFilesField;
    
    private PluginPackageOutput packageOutputField;
    
    /// <remarks/>
    public string ProjectPath {
        get {
            return this.projectPathField;
        }
        set {
            this.projectPathField = value;
        }
    }
    
    /// <remarks/>
    public PluginPrerequisites Prerequisites {
        get {
            return this.prerequisitesField;
        }
        set {
            this.prerequisitesField = value;
        }
    }
    
    /// <remarks/>
    public PluginBuildCommands BuildCommands {
        get {
            return this.buildCommandsField;
        }
        set {
            this.buildCommandsField = value;
        }
    }
    
    /// <remarks/>
    public string IncludeFiles {
        get {
            return this.includeFilesField;
        }
        set {
            this.includeFilesField = value;
        }
    }
    
    /// <remarks/>
    public string ExcludeFiles {
        get {
            return this.excludeFilesField;
        }
        set {
            this.excludeFilesField = value;
        }
    }
    
    /// <remarks/>
    public PluginPackageOutput PackageOutput {
        get {
            return this.packageOutputField;
        }
        set {
            this.packageOutputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPrerequisites {
    
    private PluginPrerequisitesKeePassVersion keePassVersionField;
    
    private bool keePassVersionFieldSpecified;
    
    private PluginPrerequisitesDotNetVersion dotNetVersionField;
    
    private bool dotNetVersionFieldSpecified;
    
    private PluginPrerequisitesOS osField;
    
    private bool osFieldSpecified;
    
    private PluginPrerequisitesPointerSize pointerSizeField;
    
    private bool pointerSizeFieldSpecified;
    
    /// <remarks/>
    public PluginPrerequisitesKeePassVersion KeePassVersion {
        get {
            return this.keePassVersionField;
        }
        set {
            this.keePassVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KeePassVersionSpecified {
        get {
            return this.keePassVersionFieldSpecified;
        }
        set {
            this.keePassVersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PluginPrerequisitesDotNetVersion DotNetVersion {
        get {
            return this.dotNetVersionField;
        }
        set {
            this.dotNetVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DotNetVersionSpecified {
        get {
            return this.dotNetVersionFieldSpecified;
        }
        set {
            this.dotNetVersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PluginPrerequisitesOS OS {
        get {
            return this.osField;
        }
        set {
            this.osField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OSSpecified {
        get {
            return this.osFieldSpecified;
        }
        set {
            this.osFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PluginPrerequisitesPointerSize PointerSize {
        get {
            return this.pointerSizeField;
        }
        set {
            this.pointerSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PointerSizeSpecified {
        get {
            return this.pointerSizeFieldSpecified;
        }
        set {
            this.pointerSizeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public enum PluginPrerequisitesKeePassVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.09")]
    Item209,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.10")]
    Item210,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.11")]
    Item211,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.12")]
    Item212,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.13")]
    Item213,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.14")]
    Item214,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.15")]
    Item215,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.16")]
    Item216,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.17")]
    Item217,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.18")]
    Item218,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.19")]
    Item219,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.20")]
    Item220,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.20.1")]
    Item2201,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.21")]
    Item221,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public enum PluginPrerequisitesDotNetVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.0")]
    Item20,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3.0")]
    Item30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3.5")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4.0")]
    Item40,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4.5")]
    Item45,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public enum PluginPrerequisitesOS {
    
    /// <remarks/>
    Windows,
    
    /// <remarks/>
    Unix,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public enum PluginPrerequisitesPointerSize {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginBuildCommands {
    
    private string preBuildField;
    
    private string postBuildField;
    
    /// <remarks/>
    public string PreBuild {
        get {
            return this.preBuildField;
        }
        set {
            this.preBuildField = value;
        }
    }
    
    /// <remarks/>
    public string PostBuild {
        get {
            return this.postBuildField;
        }
        set {
            this.postBuildField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPackageOutput {
    
    private PluginPackageOutputZip zipField;
    
    private PluginPackageOutputDeb debField;
    
    private PluginPackageOutputRpm rpmField;
    
    private PluginPackageOutputMsi msiField;
    
    private string packageNameField;
    
    private PluginPackageOutputVersionSegments versionSegmentsField;
    
    public PluginPackageOutput() {
        this.versionSegmentsField = PluginPackageOutputVersionSegments.Item3;
    }
    
    /// <remarks/>
    public PluginPackageOutputZip zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    public PluginPackageOutputDeb deb {
        get {
            return this.debField;
        }
        set {
            this.debField = value;
        }
    }
    
    /// <remarks/>
    public PluginPackageOutputRpm rpm {
        get {
            return this.rpmField;
        }
        set {
            this.rpmField = value;
        }
    }
    
    /// <remarks/>
    public PluginPackageOutputMsi msi {
        get {
            return this.msiField;
        }
        set {
            this.msiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageName {
        get {
            return this.packageNameField;
        }
        set {
            this.packageNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PluginPackageOutputVersionSegments.Item3)]
    public PluginPackageOutputVersionSegments VersionSegments {
        get {
            return this.versionSegmentsField;
        }
        set {
            this.versionSegmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPackageOutputZip {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPackageOutputDeb {
    
    private string packageRevisionField;
    
    public PluginPackageOutputDeb() {
        this.packageRevisionField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string PackageRevision {
        get {
            return this.packageRevisionField;
        }
        set {
            this.packageRevisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPackageOutputRpm {
    
    private string packageRevisionField;
    
    public PluginPackageOutputRpm() {
        this.packageRevisionField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string PackageRevision {
        get {
            return this.packageRevisionField;
        }
        set {
            this.packageRevisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public partial class PluginPackageOutputMsi {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://lechnology.com/KeePass2PluginPackagerConfig")]
public enum PluginPackageOutputVersionSegments {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}
